#+TITLE: 心理検査結果報告書

- 氏名 :: 高橋 秀羅 様
- 報告日 :: 2020 年 3 月 2 日
- 検査機関 :: 医療法人耕仁会 札幌太田病院
- 主治医 :: Dr.Y
- 検査者 :: T (公認心理師)

この度、高橋さんの困りごとの背景に、発達的な弱さ(不注意傾向や社会的コミュニケーションの弱さ)
などが関係しているかどうかを精査するため、心理検査を実施しましたので、その結果をお伝えします。

ご自身の特徴を知る為にお役立てください.


* 実施した検査

| 検査名 | 実施日              | 検査の概要                                                                                                                                                                                 |
|--------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| WAIS-4 | 2020 年 12 月 4 日  | 本検査では、言葉を使う能力、目で見た情報を処理する能力、耳から聞いた情報を覚えたり処理したりする能力、素早く作業する能力などを検査します。この検査から、得意な面、不得意な面がわかります。 |
| CAARS  | 2020 年 12 月 21 日 | 不注意の問題や、多動性-衝動性の問題がどの程度見られているかを調べる自己評価式の検査です。                                                                                                  |
| ADOS-2 | 2020 年 12 月 21 日 | 対人関係(コミュニケーション)のあり方や、限定的・反復的行動の傾向をみる検査です。                                                                                                           |



* WAIS-IV 結果
|                                    | 合成得点 | パーセンタイル順位 | 信頼区間(90%) | 記述分類             |
|------------------------------------+----------+--------------------+---------------+----------------------|
| 全検査 IQ(FSIG)                    |       95 |                 37 |         91-99 | 平均ー平均           |
| 言語理解指標(VCI) /GAI/            |      108 |                 70 |       102-113 | 平均ー平均           |
| 知覚推理指標(PRI) /GAI/            |      105 |                 63 |        99-111 | 平均ー平均           |
| ワーキングメモリー指標 (WMI) /CPI/ |       94 |                 34 |        88-100 | 平均ー平均           |
| 処理速度指標(PSI) /CPI/            |       73 |                  4 |         69-83 | 非常に低いー平均の下 |


全検査 IQ(FSIQ)は 95 でしたが、下位指憶問の開きが大きかったため、全般的知的能力をこのひと
つの指標から推論するのは控え、代替指標として、一般知的能力指標(GAI)と、認知熟達度指標(CPI)
という二つの指標を使いました。

一般知的能力指標(GAI)は 106 であり、いわゆる言語性の知的能力と視覚的推論能力は標準的であることが示唆きれました。
一方で、認知熟達度指標(CPI)は 80 であり、注意機能や心理的なコントロールを必要とするような情報処理の能力は
一般的にも高橋さんの中でも、特に弱い能力であるものと思われます。


* 総合所見
発達初期のエピソードとしては、胎児発育遅延児(2,358g)で出生し、「3歳頃に言葉の遅れがあった」
との情報がありました。小学校からは嘘をつき、それを指摘されては怒りを爆発させることを繰り返してきたとの報告もありました。

それに加えて、ミスの多さ、忘れ物・探し物の多さ、課題や作業に計画的に取り組むことの難しさ、学習の定着のしにくさ、
思考の脱線、確認を怠ることなどの不注意症状により、学業的にも職業的にも対人的にも大きな影響があったようです。

社会的コミュニケーションについては、他者の視点を全く推論できないわけではないものの、
対人関係の理解の乏しさに加え、自分の意見や知識を話しすぎる傾向があり、
いまひとつ周囲とかみ合わずにきた様子がうかがわれました。
文脈とはほ無関係に眼繁に使われる「率直な話」「敵的に言っちゃうと」などの枕詞や、
やや強迫的な話し方による話題の展開の仕方[fn:1] なども、対人関係をより堅苦しく、
ぎこちないものにさせていることが予想されます。

また、自分の考えに固執し、本来課された義務や、話題とされている事柄から逸脱してしまうことや、
自分とは異なる意見に対して悪意を感じ取って易怒的になったり、対立的な行動を起こすことから、
社会的に拡立しがちだったことがうかがえまます。

上記のような行動傾向の背景には、不注意症状や社会的コミュニケーションの弱さなどの発達的な特性が関係していることが考えられます。
また、それに加え、睡眠の問題もあることから、職場の適応は一貫して非常に困難だったものと思われます。

-----

* 今後について
** 就労について
一定程度の就労経験はありますが、対人的な齟齬によろストレスが大きいことから、
まずは、デイケアなどへの通所を経たのち、作業所などで、配虐を受けながら就労するとよいと思われます。


** 課題遂行のための十分な時間を与える
ミスの多さ、注意のそれやすき、遂行機能の弱さなどを考慮すると、
他の人と同じ時間内に同じ量と質の作業を終わらせることは難しいと思われます。
そのため、今後、なんらかので就労すろ際には、時間・量・質の点で、
配慮をしてもらうこと望ましいと考えられます。

また、必要な時に自分から質問をしたり確認することが苦手であるため、
支援者の方からこまめに声掛けをし、お互いに安心して作業をすすめることができる
環境をつくるとよいと思われます。


** 社会的スキルを身に着ける
職場での不適応には、処理能力上の弱さも関係してでいることが考えられますが、
それ以上に、対人スキルの弱さ[fn:2] が大きく関係していることが考えられます。
そのため、ソーシャルスキルトレーニング等で、
人とのより良いかかわりかたを身につけることが課題となるものと思われます。

*上記は、あくまで今回実施した心理検査から得られる、あなたの特性のー側面ですので、参考程度にとらえてでください。*

* Footnotes
[fn:1] 時系列順に話を展開する、もしくは言い直す。など。

[fn:2] 遅刻する際やした際に断り文句を言う。など。
