* What about Hidetsugu TAKAHASHI a.k.a manzyun or まんじゅ（´ん｀）?
Yoho. Appreciate README about ME.

I've only written about it as much as graffiti in the toilets of a placebo club.

This document *relies* on [[https:www.deepl.com][DeepL]].

There is no such noble thing as "self-respect" in this document.

My "self-respect" is eaten by the trolls. That nestle in people not limited to myself.

* Not Sensational Infomation
- Age :: 33
- Sex :: Male
- Real Name :: Hidetsugu TAKAHASHI / 高橋秀羅
- Names on the World Wide Web :: manzyun / まんじゅ（´ん｀）
- Current Residence :: Sapporo Hokkaido Japan
- Job :: None. Poor, foolish, and humble wonder. Undergoing rehabilitation in a social welfare program.

** Jobs History

Started working :: 2011-04-01

*** HTML, CSS
- Coded mail magazine used by Pug, Stylus, Yarn

*** PHP
- Develop about management page for system administrators used by PHP framework.
- Hacked WordPress plugins.
- Hacked WordPress template.

*** JavaScript
- Developed automation works used by Node.js
- Developed work verification scripts used by Node.js and Jasmine

*** Shell Script and PowerShell Script
- Scripting for the continuous execution of scripts created in other languages
  - Server startup script for verification in the development machine
  - Script for building the development machine environment

- Batch file name conversion script involving multiple conditions
- Batch image editing script using ImageMagick
- XML parsing and editing script

*** C#
- Creating a business support program in conjunction with SQLServer
- Creation of a business support program in conjunction with a weight scale connected to RS-232C
- Engaged in the development of a medical research auditing system from design
  - Proposed design with built-in domain-driven design.

*** Git VCS
- Using basic commands (add, commit, push, pull)
- Organize local and remote repositories (merge, rebase, filter-branch, gc, cherry-pick)
- Explaining and documenting how to use Git for people with limited understanding

*** Docker containers base virtual machine engine
- Setting up a Docker environment (including docker-machine)
- Building a Development Virtual Server with Docker
- Creating Docker images (Ubuntu, Alpine Linux)
- Building a development virtual environment with Docker Compose

*** Others
- gRPC-web implementation without Docker

** Develop environment of mine machine
- OS :: Ubuntu 23.10 x86_64
- CPU :: AMD FX-8320E (8) @ 3.200GHz
- GPU :: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
- RAM :: 32GB

** My Interesting
The whole story; the popularization of the creative act. The use of computers to aid and enhance the creative process.

*** Programming
**** Python
- Web Developing
- Increase in speed
- Embedded

It's probably the first language I've ever been able to program like that. So I'm very passionate about Python like "a baby bird that thinks the first time it was born is its parent".

**** Godot Game Engine
I became interested in programming exactly because I wanted to make video games, and that desire is still smoldering.

I'm very skeptical of the "video game brain" and "anti-videogame" mentality that is so prevalent in Japan these days, and I'd even like to make a game for those people (with a hint of irony).

Godot Engine is a free software that works on Linux, and I'm interested in it because I'm looking forward to its future development.

**** Nim
Nim is a language that I find very interesting. However, I haven't looked into it enough to be able to say anything about it.


*** Graphics
- GNU Image Manipulation Program
- Inkscape
- Krita
- Blender

I won't bother posting hyperlinks to these. But they are important tools.

*** Music
- Ardour
- LMMS
- MuseScore
- Sinsy
- Mixxx

These are also indispensable tools, but they are not used to that extent.

*** Mathematical Logic
When I turned 30, I suddenly became interested in it. Probably impressed while reading Robert M. Pirsig's "Zen and the Art of Motorcycle Maintenance" (Japanese translate edition: 「禅とオートバイ修理技術」).

I've always been incapable of writing logical sentences in Japanese, even in my own language, even though I was born and raised in Japan, so even at my age I'm having an unnecessary hard time.

To be more specific, I'm probably suffering from paranoia, schizophrenia and hyperactivity disorder. However, no doctor has ever diagnosed me as such.

* Sensational Infomation
** Psychological Examination Report
- 2021-03-02
  - [[https://github.com/manzyun/manzyun/blob/master/psychology-test-report_20210302_jp.org][Japanese (Original)]]
  - [[https://github.com/manzyun/manzyun/blob/master/psychology-test-report_20210302.org][English (Translate by DeepL)]]
** WAIS-3 Reports
- 2016-04-06
  - [[https://github.com/manzyun/manzyun/blob/master/WAIS_3_20150406-jp.org][Japanese (Original)]]
  - [[https://github.com/manzyun/manzyun/blob/master/WAIS_3_20150406.org][English (Translate by DeepL)]]

