#+TITLE: WAIST-3 Inspection Report

/This report is written for Hidetsugu. The original text of this report is in Japanese, and this document has been machine translated by DeepL and then rewritten by myself in the third person to refer to Hidetsugu./

- Subject :: TAKAHASHI Hidetsugu
- Age :: 25
- Date :: 2016-04-06
- Time Required :: 1:46
- Inspector :: John Doe (Covered)

You can see Takahashi's general intelligence and his strong and weak abilities.

* Reason for Inspection and Attitude During Inspection
To understand the characteristics of Mr. Takahashi, we conducted an inspection.  He was polite during the inspection, and I had the impression that he thought carefully before answering.

* General Intelligence
Mr. Takahashi's overall intelligence score was 99. This score is classified as "average" when compared to other people of the same age.

* Strengths and Abilities
Mr. Takahashi's strongest abilities are language comprehension and perceptual integration.
- People who are good at language comprehension are considered to be good at understanding the characteristics of things and communicating them.
- People who are good at perceptual integration are likely to be good at predicting the next task and thinking about the flow of the task.

*In daily life, I think he is good at planning and thinking of ways to work efficiently.*

* Weaknesses
Mr. Takahashi's weakest abilities are working memory and processing speed.

- Many people who have difficulty with working with working memory have trouble remembering information and organizing thoughts in their minds.
- For those with inferior processing speed capabilities, unfamiliar tasks may take much longer.

  *In his daily life, he forget how many tasks you are asked to do. It is also likely that it will take he longer to understand a task that he is doing for the first time, and he will work slower.*

* Innovations in Daily Life
- If you are asked to do a lot of work, take notes immediately and post them where _he can see them_.
  - I think he will find that he will be less likely to forget his work.
- Before him does any work, _plan his schedule on a piece of paper_.
  - He may be able to speed up the process.

- If he have trouble staying focused, don't force himself to continue working.

** Points
Measure how long he can concentrate and know how long he can concentrate. Once he know how long he can concentrate, _try to take a break before you lose your concentration_.
